### ISSUE TITLE
regarding the groq pricing

### ISSUE THREAD

**Issue by Chander88** [misbahsy/meetingmind#1]
Hi, 
In speech to text GROQ use the distil-whisper/distil-large-v3 model.

The API is free?
Because I getting the error ou exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs.

Please let me know if every thing is free.

**Comment by misbahsy** [comment]
Hey there! Yes the api is free, but have limitations. As long as your usage is within limits, it works. If not, you will have to subscribe to the paid version.
