### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by flefevre** [misbahsy/meetingmind#2]
Your project seems amazing.
Could you provide a docker file for docker compose?
Thanks

**Comment by Helion55** [comment]
Started working.

**Comment by flefevre** [comment]
Thanks a lot.
Goal is to be able to offer such service for our scientists, so they can spend more time on research for the good of planet rather on making meetings note.

**Comment by misbahsy** [comment]
Thanks to @Helion55 for the PR, closing this issue now.
