### ISSUE TITLE
Compatibility with litellm or ollama model server

### ISSUE THREAD

**Issue by flefevre** [misbahsy/meetingmind#3]
Is your project compatible with litellm or ollama servers?

**Comment by flefevre** [comment]
As I didn't get if your project has an Llm dependency, I wanted just to focus on the needs potentially to be independent of Llm providers by using a generic Llm proxy.
https://github.com/BerriAI/litellm is one of the best.

**Comment by misbahsy** [comment]
Hey there! The frontend connects with Langflow backend API, you could use any of the LLMs supported by langflow. There is also support for ollama in langflow. I have also made a few videos on how to use Ollama with Langflow, available on official langflow YT channel.
